### ISSUE TITLE
Pathwind does not launch on Ubuntu Touch Utopic #91

### ISSUE THREAD

**Issue by VictorThompson** [kenvandine/pathwind#4]
Pathwind starts with a white screen on the most recent image with Qt 5.3. This is the app log:

libust[25183/25190]: Error: Error opening shm /lttng-ust-wait-5 (in get_wait_shm
() at lttng-ust-comm.c:886)^M
libust[25183/25190]: Error: Error opening shm /lttng-ust-wait-5 (in get_wait_shm
() at lttng-ust-comm.c:886)^M
libust[25183/25191]: Error: Error opening shm /lttng-ust-wait-5-32011 (in get_wa
it_shm() at lttng-ust-comm.c:886)^M
libust[25183/25191]: Error: Error opening shm /lttng-ust-wait-5-32011 (in get_wa
it_shm() at lttng-ust-comm.c:886)^M
qrc:/InfoFlag.qml:33:5: Cannot assign object to read only list^M
callbacks 0xb4176445 0xb417633d^M
creating surface at (0, 0) with size (768, 1280) with title 'PathWind'

I assume it needs to be recompiled against Qt 5.3 libs?

**Comment by kenvandine** [comment]
Ugh, it looks like some property changed in 5.3.  Unfortunately I'm traveling, not sure when I can look at it.  Something in InfoFlag.qml if anyone wants to debug more.

**Comment by kenvandine** [comment]
I've pushed a fix to the ubuntu branch for this and uploaded a new click for review in the store.  You can grab the click for testing here https://drive.google.com/file/d/0B4LsX3vVRA8LVzZjamRSQjEtYlE/edit?usp=sharing

**Comment by VictorThompson** [comment]
Updated click works great on my Nexus 4
