### ISSUE TITLE
Muting sound in PathWind also mutes MusicApp, YouTube, etc.. etc..

### ISSUE THREAD

**Issue by tealeg** [kenvandine/pathwind#6]
So, on the BQ Aquaris 4.5 Ubuntu Edition, if you mute the sound in pathwind it pretty much kills sound from all other applications.  The only exception I've found is the ring-tone on the phone.

**Comment by kenvandine** [comment]
I'll look into it, maybe a bug in QtMultimedia?  Muting the Audio component from QtMultimedia shouldn't mute other apps, unless it should be switching on silent mode.

**Comment by tealeg** [comment]
@kenvandine right.  I was very surprised when I discovered this.

**Comment by Mangnoppa** [comment]
@tealeg Thank you for finding out, why there is no sound. I thought i did something to break it.

**Comment by kenvandine** [comment]
There is a bug somewhere in the audio stack of the platform, it's known now
and being worked on. Thanks for filing the bug!

Ken

**Comment by tealeg** [comment]
@Mangnoppa my pleasure!

@kenvandine ... also my pleasure!

**Comment by kenvandine** [comment]
The [1]ubuntu bug report has been marked as fixed, I'm closing this issue in pathwind.  The fix will be in an Ubuntu OTA update soon.
1. https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/1438486
